l_simp_chinese:
 pmg_more_local_population_population_center:"人口生产"
 pm_more_local_population_population_center:"人口基础生产"
 pmg_more_local_population_elinmination_center:"肉类生产"
 pm_more_local_population_elinmination_center:"肉类基础生产"