l_simp_chinese:
 pmg_more_local_population_population_center:"人口生产"
 pm_more_local_population_population_center_base:"基础副产物"
 pm_more_local_population_population_center_advanced:"高级副产物"
 pm_more_local_population_population_center_super:"超级副产物"
 pmg_more_local_population_elinmination_center:"肉类生产"
 pm_more_local_population_elinmination_center_base:"基础副产物"
 pm_more_local_population_elinmination_center_advanced:"高级副产物"
 pm_more_local_population_elinmination_center_super:"超级副产物"
 pm_more_local_population_elinmination_center_tremendous:"快速消灭"